main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

trailer:
  method: 'get'
  path: trailer/{slug}
  controller: App\Controller\TrailersController
  action: item